print("Question:\nSort a sentence in a particular sequence...")
income = str(input('Now...I guess give me some words so I can order them by some reason :) (separate each word with ","):'))
word1 = income.split(',')
word2 = income.split(',')
word3 = income.split(',')
word1.sort()
word2.sort(reverse= True)
word3.sort(key=len)
extra = ','
outcome1 = extra.join(word1)
outcome2 = extra.join(word2)
outcome3 = extra.join(word3)
print('\nSorted list (alphabetically):', outcome1)
print('\nSorted list (reverse alphabetically):', outcome2)
print('\nSorted list (in length):', outcome3)